<?php

namespace WebinoData;

use Zend\Db\TableGateway\TableGateway;

/**
 * Test class for DataService.
 * Generated by PHPUnit on 2013-04-13 at 20:22:09.
 */
class DataServiceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var DataService
     */
    protected $object;

    /**
     * @var TableGateway
     */
    protected $table;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->table = $this->getMock(TableGateway::class, [], [], '', false);
        $config = [];
        $this->object = new DataService($this->table, $config);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers \WebinoData\DataService::getLastInsertValue
     * @todo Implement testGetLastInsertValue().
     */
    public function testGetLastInsertValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \WebinoData\DataService::getTableName
     * @todo Implement testGetTableName().
     */
    public function testGetTableName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \WebinoData\DataService::getEvent
     * @todo Implement testGetEvent().
     */
    public function testGetEvent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \WebinoData\DataService::setEvent
     * @todo Implement testSetEvent().
     */
    public function testSetEvent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \WebinoData\DataService::getEventManager
     * @todo Implement testGetEventManager().
     */
    public function testGetEventManager()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \WebinoData\DataService::setEventManager
     * @todo Implement testSetEventManager().
     */
    public function testSetEventManager()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \WebinoData\DataService::getServiceManager
     * @todo Implement testGetServiceManager().
     */
    public function testGetServiceManager()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \WebinoData\DataService::setServiceManager
     * @todo Implement testSetServiceManager().
     */
    public function testSetServiceManager()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \WebinoData\DataService::getPlatform
     * @todo Implement testGetPlatform().
     */
    public function testGetPlatform()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \WebinoData\DataService::setPlatform
     * @todo Implement testSetPlatform().
     */
    public function testSetPlatform()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \WebinoData\DataService::getInputFilterFactory
     * @todo Implement testGetInputFilterFactory().
     */
    public function testGetInputFilterFactory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \WebinoData\DataService::setInputFilterFactory
     * @todo Implement testSetInputFilterFactory().
     */
    public function testSetInputFilterFactory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \WebinoData\DataService::getInputFilter
     * @todo Implement testGetInputFilter().
     */
    public function testGetInputFilter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \WebinoData\DataService::setInputFilter
     * @todo Implement testSetInputFilter().
     */
    public function testSetInputFilter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \WebinoData\DataService::setHasOne
     * @todo Implement testSetHasOne().
     */
    public function testSetHasOne()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \WebinoData\DataService::hasOne
     * @todo Implement testHasOne().
     */
    public function testHasOne()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \WebinoData\DataService::one
     * @todo Implement testOne().
     */
    public function testOne()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \WebinoData\DataService::setHasMany
     * @todo Implement testSetHasMany().
     */
    public function testSetHasMany()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \WebinoData\DataService::hasMany
     * @todo Implement testHasMany().
     */
    public function testHasMany()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \WebinoData\DataService::many
     * @todo Implement testMany().
     */
    public function testMany()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \WebinoData\DataService::bind
     * @todo Implement testBind().
     */
    public function testBind()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \WebinoData\DataService::getQuery
     * @todo Implement testGetQuery().
     */
    public function testGetQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \WebinoData\DataService::setQuery
     * @todo Implement testSetQuery().
     */
    public function testSetQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \WebinoData\DataService::select
     * @todo Implement testSelect().
     */
    public function testSelect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \WebinoData\DataService::configSelect
     * @todo Implement testConfigSelect().
     */
    public function testConfigSelect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \WebinoData\DataService::fetch
     * @todo Implement testFetch().
     */
    public function testFetch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \WebinoData\DataService::fetchWith
     * @todo Implement testFetchWith().
     */
    public function testFetchWith()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \WebinoData\DataService::delete
     * @todo Implement testDelete().
     */
    public function testDelete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \WebinoData\DataService::fetchJust
     * @todo Implement testFetchJust().
     */
    public function testFetchJust()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \WebinoData\DataService::fetchLike
     * @todo Implement testFetchLike().
     */
    public function testFetchLike()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \WebinoData\DataService::own
     * @todo Implement testOwn().
     */
    public function testOwn()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \WebinoData\DataService::owned
     * @todo Implement testOwned().
     */
    public function testOwned()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \WebinoData\DataService::validate
     * @todo Implement testValidate().
     */
    public function testValidate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \WebinoData\DataService::getArrayCopy
     * @todo Implement testGetArrayCopy().
     */
    public function testGetArrayCopy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \WebinoData\DataService::exchangeArray
     * @todo Implement testExchange[].
     */
    public function testExchangeArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \WebinoData\DataService::executeQuery
     * @todo Implement testExecuteQuery().
     */
    public function testExecuteQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \WebinoData\DataService::toggle
     * @todo Implement testToggle().
     */
    public function testToggle()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \WebinoData\DataService::increment
     * @todo Implement testIncrement().
     */
    public function testIncrement()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \WebinoData\DataService::decrement
     * @todo Implement testDecrement().
     */
    public function testDecrement()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
