<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'WebinoData\Module'                                       => __DIR__ . '/src/WebinoData/Module.php',
    'WebinoData\DataEvent'                                    => __DIR__ . '/src/WebinoData/DataEvent.php',
    'WebinoData\Paginator\Adapter\WebinoDataSelect'           => __DIR__ . '/src/WebinoData/Paginator/Adapter/WebinoDataSelect.php',
    'WebinoData\Exception\ExceptionInterface'                 => __DIR__ . '/src/WebinoData/Exception/ExceptionInterface.php',
    'WebinoData\Exception\InvalidArgumentException'           => __DIR__ . '/src/WebinoData/Exception/InvalidArgumentException.php',
    'WebinoData\Exception\MissingPropertyException'           => __DIR__ . '/src/WebinoData/Exception/MissingPropertyException.php',
    'WebinoData\Exception\RuntimeException'                   => __DIR__ . '/src/WebinoData/Exception/RuntimeException.php',
    'WebinoData\DataService'                                  => __DIR__ . '/src/WebinoData/DataService.php',
    'WebinoData\DataQuery'                                    => __DIR__ . '/src/WebinoData/DataQuery.php',
    'WebinoData\DataSelect'                                   => __DIR__ . '/src/WebinoData/DataSelect.php',
    'WebinoData\InputFilter\InputFilterFactoryAwareInterface' => __DIR__ . '/src/WebinoData/InputFilter/InputFilterFactoryAwareInterface.php',
    'WebinoData\DataPlugin\Relations'                         => __DIR__ . '/src/WebinoData/DataPlugin/Relations.php',
    'WebinoData\DataQuery\Decrement'                          => __DIR__ . '/src/WebinoData/DataQuery/Decrement.php',
    'WebinoData\DataQuery\Increment'                          => __DIR__ . '/src/WebinoData/DataQuery/Increment.php',
    'WebinoData\DataQuery\AbstractDataQuery'                  => __DIR__ . '/src/WebinoData/DataQuery/AbstractDataQuery.php',
    'WebinoData\DataQuery\Toggle'                             => __DIR__ . '/src/WebinoData/DataQuery/Toggle.php',
);
